import dynamic from "next/dynamic";
import Head from "next/head";
import Header from "../components/header";
import NavItem from "../components/navItem";
import styles from "../styles/Home.module.css";
const BackgroundWrapper = dynamic(
  () => import("../components/backgroundWrapper"),
  { loading: () => <p>Loading...</p> }
);

export default function Home() {
  return (
    <BackgroundWrapper backgroundImage="/program/canvasHome.png">
      <div className={styles.container}>
        <Head>
          <title>Quiz App</title>
          <meta
            name="description"
            content="Generated by create next app Quiz App"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <main className={styles.main}>
          <div className="flex flex-row flex-wrap justify-center gap-6">
            <NavItem sectionName="technology" />
            <NavItem sectionName="culture" />
            <NavItem sectionName="moto" />
            <NavItem sectionName="program" />
            <NavItem sectionName="history" />
          </div>
        </main>

        {/* <footer className={styles.footer}>Footer</footer> */}
      </div>
    </BackgroundWrapper>
  );
}
